<?php

namespace AppBundle\Repository;

/**
 * EntryTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
