<?php

namespace AppBundle\Repository;

/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param \DateTime $date
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function ticketsSoldOnChosenDate(\DateTime $date)
    {
        $qb = $this
            ->createQueryBuilder('purchase')
            ->innerJoin('purchase.tickets', 'sold','WITH', 'purchase.dateOfVisit = :date')
            ->select('COUNT(sold)')
            ->setParameter('date',$date)
        ;
        return $qb->getQuery()->getSingleScalarResult();
    }

}
