<?php

namespace AppBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends \Doctrine\ORM\EntityRepository
{
    public function ticketsSoldOnChosenDate($date)
	{
		$qb = $this->createQueryBuilder('purchase');
        $qb->select('COUNT(purchase.tickets)')
            ->where('purchase.date = :date')
            ->setParameter('date', $date);
	}
}
